const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./endpoints.js']

const doc = {
    info: {
        version: "0.0.1",
        title: "IoT API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },

    definitions: {
        device: {
                "did": "room1",
                "status": true,
                "value": 70
              },
              did:"room1"
    }
}


swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./index.js')
})